config/routes.rb
App::Application.routes.draw do
  resources :problems

  resources :questiongroupquestions

  resources :questiongroups

  resources :answer_switches

  resources :set_compilation_links

  resources :setcompilations

  resources :texts

  resources :setquestionlinks

  resources :questionsets

  get "coaching/welcome", to: 'coaching#index'
  get "coaching/start", to: "coaching#start"
  post "coaching", to: "coaching#coaching"
  post "coaching/addQPCount", to: "coaching#addQPCount"
  post "coaching/getNextGroupItem", to: "coaching#getNextGroupItem"
  get "index/home"
  get "index/about"
  
  resources :session_answers

  resources :answers

  resources :questions

  resources :sessions

  resources :users
  
  resources :coaching 

  root 'index#home'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	has_one :question

	def interpret(against)
	
		case against
			when true
				if self.text.include? "Ja" or self.text.include? 'Jau' or self.text.include? "jap" or self.text.include? "gut" or self.text.include? "yes"
					Rails.logger.debug("Habe gechecked Ergebnis: Positiv: true !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 1
				else
					Rails.logger.debug("Habe gechecked Ergebnis: Positiv: false !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 0
				end
			when false
				if self.text.include? "kein" or self.text.include? 'nein' or self.text.include? "nicht" or self.text.include? "schlecht" or self.text.include? "no"
					Rails.logger.debug("Habe gechecked Ergebnis: Negativ: true !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 1
				else
					Rails.logger.debug("Habe gechecked Ergebnis: Negativ: false !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 0
				end
			else
				return nil
		end
	end
end

app/models/answer_switch.rb
class AnswerSwitch < ActiveRecord::Base
end

app/models/coaching.rb
class Coaching < ActiveRecord::Base
	
	def getNextQuestion(@parentQuestion)
  	Setquestionlink.find_by question_id: @parentQuestion  	
  end

end

app/models/helptext.rb
class Helptext < ActiveRecord::Base
end

app/models/problem.rb
class Problem < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	has_many :setquestionlinks
	
	def add
	
	end
	
	def insertion(sId, setItemId) 
		if(self.needs_insertion)
			@insertion = Answer.find_by_sql(%Q(SELECT answers.* FROM answers JOIN session_answers on session_answers.answer_id = answers.id AND session_answers.session_id = #{sId} WHERE setItemId = #{self.answer_of_setItem}))
			self.text["$$$"] = @insertion[0].text
		end		
	end

end

app/models/questiongroup.rb
class Questiongroup < ActiveRecord::Base
end

app/models/questionproblem.rb
class Questionproblem < ActiveRecord::Base
end

app/models/questionset.rb
class Questionset < ActiveRecord::Base

	belongs_to :setquestionlink

	def getNextQuestionId(set, preQuestionId)
		@qset = setquestionlink.find_by(:set_id) 
		@qset = Questionset.find(:set)
		@question 
	end
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :user
end

app/models/session_answer.rb
class SessionAnswer < ActiveRecord::Base
	has_many	:answers
	has_many	:sessions
end

app/models/setItem.rb
class Setitem < ActiveRecord::Base

	has_many :questions
	has_many :texts
	has_many :groups

end

app/models/setcompilation.rb
class Setcompilation < ActiveRecord::Base

end

app/models/text.rb
class Text < ActiveRecord::Base

	def insertion(sId, setItemId) 
		if(self.needs_insertion)
				@insertion = Answer.find_by_sql(%Q(SELECT answers.* FROM answers JOIN session_answers on session_answers.answer_id = answers.id AND session_answers.session_id = #{sId} WHERE setItemId = #{self.answer_of_setItem}))
				self.text["$$$"] = @insertion[0].text
		end		
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sessions
end

app/controllers/answer_switches_controller.rb
class AnswerSwitchesController < ApplicationController
  before_action :set_answer_switch, only: [:show, :edit, :update, :destroy]

  # GET /answer_switches
  # GET /answer_switches.json
  def index
    @answer_switches = AnswerSwitch.all
  end

  # GET /answer_switches/1
  # GET /answer_switches/1.json
  def show
  end

  # GET /answer_switches/new
  def new
    @answer_switch = AnswerSwitch.new
  end

  # GET /answer_switches/1/edit
  def edit
  end

  # POST /answer_switches
  # POST /answer_switches.json
  def create
    @answer_switch = AnswerSwitch.new(answer_switch_params)

    respond_to do |format|
      if @answer_switch.save
        format.html { redirect_to @answer_switch, notice: 'Answer switch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer_switch }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer_switch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answer_switches/1
  # PATCH/PUT /answer_switches/1.json
  def update
    respond_to do |format|
      if @answer_switch.update(answer_switch_params)
        format.html { redirect_to @answer_switch, notice: 'Answer switch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer_switch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answer_switches/1
  # DELETE /answer_switches/1.json
  def destroy
    @answer_switch.destroy
    respond_to do |format|
      format.html { redirect_to answer_switches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer_switch
      @answer_switch = AnswerSwitch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_switch_params
      params.require(:answer_switch).permit(:question_id, :answer, :nextQuestion)
    end
end

app/helpers/answer_switches_helper.rb
module AnswerSwitchesHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answer_switches/_form.html.erb
<%= form_for(@answer_switch) do |f| %>
  <% if @answer_switch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer_switch.errors.count, "error") %> prohibited this answer_switch from being saved:</h2>

      <ul>
      <% @answer_switch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :nextQuestion %><br>
    <%= f.number_field :nextQuestion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answer_switches/edit.html.erb
<h1>Editing answer_switch</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer_switch %> |
<%= link_to 'Back', answer_switches_path %>

app/views/answer_switches/index.html.erb
<h1>Listing answer_switches</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Nextquestion</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @answer_switches.each do |answer_switch| %>
      <tr>
        <td><%= answer_switch.question_id %></td>
        <td><%= answer_switch.answer %></td>
        <td><%= answer_switch.nextQuestion %></td>
        <td><%= link_to 'Show', answer_switch %></td>
        <td><%= link_to 'Edit', edit_answer_switch_path(answer_switch) %></td>
        <td><%= link_to 'Destroy', answer_switch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer switch', new_answer_switch_path %>

app/views/answer_switches/new.html.erb
<h1>New answer_switch</h1>

<%= render 'form' %>

<%= link_to 'Back', answer_switches_path %>

app/views/answer_switches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer_switch.question_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @answer_switch.answer %>
</p>

<p>
  <strong>Nextquestion:</strong>
  <%= @answer_switch.nextQuestion %>
</p>

<%= link_to 'Edit', edit_answer_switch_path(@answer_switch) %> |
<%= link_to 'Back', answer_switches_path %>