config/routes.rb
App::Application.routes.draw do
  resources :problems

  resources :questiongroupquestions

  resources :questiongroups

  resources :answer_switches

  resources :set_compilation_links

  resources :setcompilations

  resources :texts

  resources :setquestionlinks

  resources :questionsets

  get "coaching/welcome", to: 'coaching#index'
  get "coaching/start", to: "coaching#start"
  post "coaching", to: "coaching#coaching"
  post "coaching/addQPCount", to: "coaching#addQPCount"
  post "coaching/getNextGroupItem", to: "coaching#getNextGroupItem"
  get "index/home"
  get "index/about"
  
  resources :session_answers

  resources :answers

  resources :questions

  resources :sessions

  resources :users
  
  resources :coaching 

  root 'index#home'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	has_one :question

	def interpret(against)
	
		case against
			when true
				if self.text.include? "Ja" or self.text.include? 'Jau' or self.text.include? "jap" or self.text.include? "gut" or self.text.include? "yes"
					Rails.logger.debug("Habe gechecked Ergebnis: Positiv: true !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 1
				else
					Rails.logger.debug("Habe gechecked Ergebnis: Positiv: false !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 0
				end
			when false
				if self.text.include? "kein" or self.text.include? 'nein' or self.text.include? "nicht" or self.text.include? "schlecht" or self.text.include? "no"
					Rails.logger.debug("Habe gechecked Ergebnis: Negativ: true !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 1
				else
					Rails.logger.debug("Habe gechecked Ergebnis: Negativ: false !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 0
				end
			else
				return nil
		end
	end
end

app/models/answer_switch.rb
class AnswerSwitch < ActiveRecord::Base
end

app/models/coaching.rb
class Coaching < ActiveRecord::Base
	
	def getNextQuestion(@parentQuestion)
  	Setquestionlink.find_by question_id: @parentQuestion  	
  end

end

app/models/helptext.rb
class Helptext < ActiveRecord::Base
end

app/models/problem.rb
class Problem < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	has_many :setquestionlinks
	
	def add
	
	end
	
	def insertion(sId, setItemId) 
		if(self.needs_insertion)
			@insertion = Answer.find_by_sql(%Q(SELECT answers.* FROM answers JOIN session_answers on session_answers.answer_id = answers.id AND session_answers.session_id = #{sId} WHERE setItemId = #{self.answer_of_setItem}))
			self.text["$$$"] = @insertion[0].text
		end		
	end

end

app/models/questiongroup.rb
class Questiongroup < ActiveRecord::Base
end

app/models/questionproblem.rb
class Questionproblem < ActiveRecord::Base
end

app/models/questionset.rb
class Questionset < ActiveRecord::Base

	belongs_to :setquestionlink

	def getNextQuestionId(set, preQuestionId)
		@qset = setquestionlink.find_by(:set_id) 
		@qset = Questionset.find(:set)
		@question 
	end
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :user
end

app/models/session_answer.rb
class SessionAnswer < ActiveRecord::Base
	has_many	:answers
	has_many	:sessions
end

app/models/setItem.rb
class Setitem < ActiveRecord::Base

	has_many :questions
	has_many :texts
	has_many :groups

end

app/models/setcompilation.rb
class Setcompilation < ActiveRecord::Base

end

app/models/text.rb
class Text < ActiveRecord::Base

	def insertion(sId, setItemId) 
		if(self.needs_insertion)
				@insertion = Answer.find_by_sql(%Q(SELECT answers.* FROM answers JOIN session_answers on session_answers.answer_id = answers.id AND session_answers.session_id = #{sId} WHERE setItemId = #{self.answer_of_setItem}))
				self.text["$$$"] = @insertion[0].text
		end		
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sessions
end

app/controllers/setcompilations_controller.rb
class SetcompilationsController < ApplicationController
  before_action :set_setcompilation, only: [:show, :edit, :update, :destroy]

  # GET /setcompilations
  # GET /setcompilations.json
  def index
    @setcompilations = Setcompilation.all
  end

  # GET /setcompilations/1
  # GET /setcompilations/1.json
  def show
  end

  # GET /setcompilations/new
  def new
    @setcompilation = Setcompilation.new
  end

  # GET /setcompilations/1/edit
  def edit
  end

  # POST /setcompilations
  # POST /setcompilations.json
  def create
    @setcompilation = Setcompilation.new(setcompilation_params)

    respond_to do |format|
      if @setcompilation.save
        format.html { redirect_to @setcompilation, notice: 'Setcompilation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @setcompilation }
      else
        format.html { render action: 'new' }
        format.json { render json: @setcompilation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setcompilations/1
  # PATCH/PUT /setcompilations/1.json
  def update
    respond_to do |format|
      if @setcompilation.update(setcompilation_params)
        format.html { redirect_to @setcompilation, notice: 'Setcompilation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @setcompilation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setcompilations/1
  # DELETE /setcompilations/1.json
  def destroy
    @setcompilation.destroy
    respond_to do |format|
      format.html { redirect_to setcompilations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setcompilation
      @setcompilation = Setcompilation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setcompilation_params
      params.require(:setcompilation).permit(:name, :theme)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/setcompilations_helper.rb
module SetcompilationsHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/setcompilations/_form.html.erb
<%= form_for(@setcompilation) do |f| %>
  <% if @setcompilation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setcompilation.errors.count, "error") %> prohibited this setcompilation from being saved:</h2>

      <ul>
      <% @setcompilation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/setcompilations/edit.html.erb
<h1>Editing setcompilation</h1>

<%= render 'form' %>

<%= link_to 'Show', @setcompilation %> |
<%= link_to 'Back', setcompilations_path %>

app/views/setcompilations/index.html.erb
<h1>Listing setcompilations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Theme</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @setcompilations.each do |setcompilation| %>
      <tr>
        <td><%= setcompilation.name %></td>
        <td><%= setcompilation.theme %></td>
        <td><%= link_to 'Show', setcompilation %></td>
        <td><%= link_to 'Edit', edit_setcompilation_path(setcompilation) %></td>
        <td><%= link_to 'Destroy', setcompilation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setcompilation', new_setcompilation_path %>

app/views/setcompilations/new.html.erb
<h1>New setcompilation</h1>

<%= render 'form' %>

<%= link_to 'Back', setcompilations_path %>

app/views/setcompilations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @setcompilation.name %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @setcompilation.theme %>
</p>

<%= link_to 'Edit', edit_setcompilation_path(@setcompilation) %> |
<%= link_to 'Back', setcompilations_path %>