config/routes.rb
App::Application.routes.draw do
  resources :problems

  resources :questiongroupquestions

  resources :questiongroups

  resources :answer_switches

  resources :set_compilation_links

  resources :setcompilations

  resources :texts

  resources :setquestionlinks

  resources :questionsets

  get "coaching/welcome", to: 'coaching#index'
  get "coaching/start", to: "coaching#start"
  post "coaching", to: "coaching#coaching"
  post "coaching/addQPCount", to: "coaching#addQPCount"
  post "coaching/getNextGroupItem", to: "coaching#getNextGroupItem"
  get "index/home"
  get "index/about"
  
  resources :session_answers

  resources :answers

  resources :questions

  resources :sessions

  resources :users
  
  resources :coaching 

  root 'index#home'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	has_one :question

	def interpret(against)
	
		case against
			when true
				if self.text.include? "Ja" or self.text.include? 'Jau' or self.text.include? "jap" or self.text.include? "gut" or self.text.include? "yes"
					Rails.logger.debug("Habe gechecked Ergebnis: Positiv: true !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 1
				else
					Rails.logger.debug("Habe gechecked Ergebnis: Positiv: false !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 0
				end
			when false
				if self.text.include? "kein" or self.text.include? 'nein' or self.text.include? "nicht" or self.text.include? "schlecht" or self.text.include? "no"
					Rails.logger.debug("Habe gechecked Ergebnis: Negativ: true !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 1
				else
					Rails.logger.debug("Habe gechecked Ergebnis: Negativ: false !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 0
				end
			else
				return nil
		end
	end
end

app/models/answer_switch.rb
class AnswerSwitch < ActiveRecord::Base
end

app/models/coaching.rb
class Coaching < ActiveRecord::Base
	
	def getNextQuestion(@parentQuestion)
  	Setquestionlink.find_by question_id: @parentQuestion  	
  end

end

app/models/helptext.rb
class Helptext < ActiveRecord::Base
end

app/models/problem.rb
class Problem < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	has_many :setquestionlinks
	
	def add
	
	end
	
	def insertion(sId, setItemId) 
		if(self.needs_insertion)
			@insertion = Answer.find_by_sql(%Q(SELECT answers.* FROM answers JOIN session_answers on session_answers.answer_id = answers.id AND session_answers.session_id = #{sId} WHERE setItemId = #{self.answer_of_setItem}))
			self.text["$$$"] = @insertion[0].text
		end		
	end

end

app/models/questiongroup.rb
class Questiongroup < ActiveRecord::Base
end

app/models/questionproblem.rb
class Questionproblem < ActiveRecord::Base
end

app/models/questionset.rb
class Questionset < ActiveRecord::Base

	belongs_to :setquestionlink

	def getNextQuestionId(set, preQuestionId)
		@qset = setquestionlink.find_by(:set_id) 
		@qset = Questionset.find(:set)
		@question 
	end
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :user
end

app/models/session_answer.rb
class SessionAnswer < ActiveRecord::Base
	has_many	:answers
	has_many	:sessions
end

app/models/setItem.rb
class Setitem < ActiveRecord::Base

	has_many :questions
	has_many :texts
	has_many :groups

end

app/models/setcompilation.rb
class Setcompilation < ActiveRecord::Base

end

app/models/text.rb
class Text < ActiveRecord::Base

	def insertion(sId, setItemId) 
		if(self.needs_insertion)
				@insertion = Answer.find_by_sql(%Q(SELECT answers.* FROM answers JOIN session_answers on session_answers.answer_id = answers.id AND session_answers.session_id = #{sId} WHERE setItemId = #{self.answer_of_setItem}))
				self.text["$$$"] = @insertion[0].text
		end		
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sessions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:text, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Question</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.text %></td>
        <td><%= answer.question_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @answer.text %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>