config/routes.rb
App::Application.routes.draw do
  resources :problems

  resources :questiongroupquestions

  resources :questiongroups

  resources :answer_switches

  resources :set_compilation_links

  resources :setcompilations

  resources :texts

  resources :setquestionlinks

  resources :questionsets

  get "coaching/welcome", to: 'coaching#index'
  get "coaching/start", to: "coaching#start"
  post "coaching", to: "coaching#coaching"
  post "coaching/addQPCount", to: "coaching#addQPCount"
  post "coaching/getNextGroupItem", to: "coaching#getNextGroupItem"
  get "index/home"
  get "index/about"
  
  resources :session_answers

  resources :answers

  resources :questions

  resources :sessions

  resources :users
  
  resources :coaching 

  root 'index#home'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	has_one :question

	def interpret(against)
	
		case against
			when true
				if self.text.include? "Ja" or self.text.include? 'Jau' or self.text.include? "jap" or self.text.include? "gut" or self.text.include? "yes"
					Rails.logger.debug("Habe gechecked Ergebnis: Positiv: true !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 1
				else
					Rails.logger.debug("Habe gechecked Ergebnis: Positiv: false !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 0
				end
			when false
				if self.text.include? "kein" or self.text.include? 'nein' or self.text.include? "nicht" or self.text.include? "schlecht" or self.text.include? "no"
					Rails.logger.debug("Habe gechecked Ergebnis: Negativ: true !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 1
				else
					Rails.logger.debug("Habe gechecked Ergebnis: Negativ: false !!! ---------------- ---------------- ---------------- ---------------- ----------------")
					return 0
				end
			else
				return nil
		end
	end
end

app/models/answer_switch.rb
class AnswerSwitch < ActiveRecord::Base
end

app/models/coaching.rb
class Coaching < ActiveRecord::Base
	
	def getNextQuestion(@parentQuestion)
  	Setquestionlink.find_by question_id: @parentQuestion  	
  end

end

app/models/helptext.rb
class Helptext < ActiveRecord::Base
end

app/models/problem.rb
class Problem < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	has_many :setquestionlinks
	
	def add
	
	end
	
	def insertion(sId, setItemId) 
		if(self.needs_insertion)
			@insertion = Answer.find_by_sql(%Q(SELECT answers.* FROM answers JOIN session_answers on session_answers.answer_id = answers.id AND session_answers.session_id = #{sId} WHERE setItemId = #{self.answer_of_setItem}))
			self.text["$$$"] = @insertion[0].text
		end		
	end

end

app/models/questiongroup.rb
class Questiongroup < ActiveRecord::Base
end

app/models/questionproblem.rb
class Questionproblem < ActiveRecord::Base
end

app/models/questionset.rb
class Questionset < ActiveRecord::Base

	belongs_to :setquestionlink

	def getNextQuestionId(set, preQuestionId)
		@qset = setquestionlink.find_by(:set_id) 
		@qset = Questionset.find(:set)
		@question 
	end
end

app/models/session.rb
class Session < ActiveRecord::Base
	belongs_to :user
end

app/models/session_answer.rb
class SessionAnswer < ActiveRecord::Base
	has_many	:answers
	has_many	:sessions
end

app/models/setItem.rb
class Setitem < ActiveRecord::Base

	has_many :questions
	has_many :texts
	has_many :groups

end

app/models/set_compilation_link.rb
class SetCompilationLink < ActiveRecord::Base

	has_many :questionsets

	def getNextSet(currentSet)
		find_by(:set_id => currentSet)
	end
end

app/models/setcompilation.rb
class Setcompilation < ActiveRecord::Base

end

app/models/text.rb
class Text < ActiveRecord::Base

	def insertion(sId, setItemId) 
		if(self.needs_insertion)
				@insertion = Answer.find_by_sql(%Q(SELECT answers.* FROM answers JOIN session_answers on session_answers.answer_id = answers.id AND session_answers.session_id = #{sId} WHERE setItemId = #{self.answer_of_setItem}))
				self.text["$$$"] = @insertion[0].text
		end		
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sessions
end

app/controllers/set_compilation_links_controller.rb
class SetCompilationLinksController < ApplicationController
  before_action :set_set_compilation_link, only: [:show, :edit, :update, :destroy]

  # GET /set_compilation_links
  # GET /set_compilation_links.json
  def index
    @set_compilation_links = SetCompilationLink.all
  end

  # GET /set_compilation_links/1
  # GET /set_compilation_links/1.json
  def show
  end

  # GET /set_compilation_links/new
  def new
    @set_compilation_link = SetCompilationLink.new
  end

  # GET /set_compilation_links/1/edit
  def edit
  end

  # POST /set_compilation_links
  # POST /set_compilation_links.json
  def create
    @set_compilation_link = SetCompilationLink.new(set_compilation_link_params)

    respond_to do |format|
      if @set_compilation_link.save
        format.html { redirect_to @set_compilation_link, notice: 'Set compilation link was successfully created.' }
        format.json { render action: 'show', status: :created, location: @set_compilation_link }
      else
        format.html { render action: 'new' }
        format.json { render json: @set_compilation_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /set_compilation_links/1
  # PATCH/PUT /set_compilation_links/1.json
  def update
    respond_to do |format|
      if @set_compilation_link.update(set_compilation_link_params)
        format.html { redirect_to @set_compilation_link, notice: 'Set compilation link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @set_compilation_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /set_compilation_links/1
  # DELETE /set_compilation_links/1.json
  def destroy
    @set_compilation_link.destroy
    respond_to do |format|
      format.html { redirect_to set_compilation_links_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_set_compilation_link
      @set_compilation_link = SetCompilationLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def set_compilation_link_params
      params.require(:set_compilation_link).permit(:set_id, :setcompilation_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/set_compilation_links_helper.rb
module SetCompilationLinksHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/set_compilation_links/_form.html.erb
<%= form_for(@set_compilation_link) do |f| %>
  <% if @set_compilation_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@set_compilation_link.errors.count, "error") %> prohibited this set_compilation_link from being saved:</h2>

      <ul>
      <% @set_compilation_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :set_id %><br>
    <%= f.number_field :set_id %>
  </div>
  <div class="field">
    <%= f.label :setcompilation_id %><br>
    <%= f.number_field :setcompilation_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/set_compilation_links/edit.html.erb
<h1>Editing set_compilation_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @set_compilation_link %> |
<%= link_to 'Back', set_compilation_links_path %>

app/views/set_compilation_links/index.html.erb
<h1>Listing set_compilation_links</h1>

<table>
  <thead>
    <tr>
      <th>Set</th>
      <th>Setcompilation</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @set_compilation_links.each do |set_compilation_link| %>
      <tr>
        <td><%= set_compilation_link.set_id %></td>
        <td><%= set_compilation_link.setcompilation_id %></td>
        <td><%= link_to 'Show', set_compilation_link %></td>
        <td><%= link_to 'Edit', edit_set_compilation_link_path(set_compilation_link) %></td>
        <td><%= link_to 'Destroy', set_compilation_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Set compilation link', new_set_compilation_link_path %>

app/views/set_compilation_links/new.html.erb
<h1>New set_compilation_link</h1>

<%= render 'form' %>

<%= link_to 'Back', set_compilation_links_path %>

app/views/set_compilation_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Set:</strong>
  <%= @set_compilation_link.set_id %>
</p>

<p>
  <strong>Setcompilation:</strong>
  <%= @set_compilation_link.setcompilation_id %>
</p>

<%= link_to 'Edit', edit_set_compilation_link_path(@set_compilation_link) %> |
<%= link_to 'Back', set_compilation_links_path %>